// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using userlogin.Models;

namespace userlogin.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20180629191502_base1")]
    partial class base1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("userlogin.Models.Auction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("creatorId");

                    b.Property<string>("description")
                        .IsRequired();

                    b.Property<DateTime>("expiration");

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("creatorId");

                    b.ToTable("auctions");
                });

            modelBuilder.Entity("userlogin.Models.Bid", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("amount");

                    b.Property<int>("auctionId");

                    b.Property<DateTime>("created_at");

                    b.Property<int>("creatorId");

                    b.HasKey("id");

                    b.HasIndex("auctionId");

                    b.HasIndex("creatorId");

                    b.ToTable("bids");
                });

            modelBuilder.Entity("userlogin.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.Property<float>("wallet");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("userlogin.Models.Auction", b =>
                {
                    b.HasOne("userlogin.Models.User", "creator")
                        .WithMany()
                        .HasForeignKey("creatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("userlogin.Models.Bid", b =>
                {
                    b.HasOne("userlogin.Models.Auction", "auction")
                        .WithMany("bids")
                        .HasForeignKey("auctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("userlogin.Models.User", "creator")
                        .WithMany()
                        .HasForeignKey("creatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
